services:


  # --------------------------------------------------
  # Superset
  # --------------------------------------------------

  uft-superset:
    image: uft-superset:develop
    restart: unless-stopped

    ports:
      - "8088:8088"

    environment:

      POSTGRES_HOST: "host.docker.internal"
      POSTGRES_PORT: "5433"
      POSTGRES_DATABASE: "uft_superset-demo"
      POSTGRES_USER: "superset"
      POSTGRES_PASSWORD: "superset"



      SUPERSET_ADMIN_USERNAME: "admin"
      SUPERSET_ADMIN_FIRSTNAME: "Ravi"
      SUPERSET_ADMIN_LASTNAME: "Pratap"
      SUPERSET_ADMIN_EMAIL: "rpratap@uft-int.com"
      SUPERSET_ADMIN_PASSWORD: "Test@123"

      SUPERSET_SECRET_KEY: "K8vQ2mZ7xR4pL9nT6wY3cF5hJ1sD8aB0eN6uX4gP2rV9kM7q"

      GUEST_TOKEN_JWT_SECRET: "f4N8xQ2mL7vR9kT3pW6zY1cD5sH8jB0eU4gA7nX2qM9"
      GUEST_TOKEN_JWT_AUDIENCE: "uft"

      CLICKHOUSE_HOST: "host.docker.internal"
      CLICKHOUSE_PORT: "8123"
      CLICKHOUSE_DATABASE: "return_settlements"
      CLICKHOUSE_USERNAME: "admin"
      CLICKHOUSE_PASSWORD: "admin"

    volumes:
      - uft_superset_home:/app/superset_home

volumes:
  uft_superset_home:
